services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: conduit-api

    env_file:
      - ./config/.env

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    restart: unless-stopped

    stdin_open: true
    tty: true
