# Generated by Django 6.0.6 on 2026-07-20 06:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[("hydrology", "Hydrology"), ("livestock", "Livestock")], max_length=20
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("runoff_risk_score", models.FloatField(blank=True, null=True)),
                ("rainfall_summary", models.JSONField(blank=True, null=True)),
                (
                    "pressure_trend",
                    models.CharField(
                        blank=True,
                        choices=[("rising", "Rising"), ("falling", "Falling"), ("steady", "Steady")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("recommendation", models.CharField(blank=True, default="", max_length=255)),
                ("wbgt_value", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="telemetry.weatherstation",
                    ),
                ),
                (
                    "triggering_measurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="telemetry.weathermeasurement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["station", "alert_type", "is_active"], name="alerts_aler_station_eb5e26_idx"
                    )
                ],
            },
        ),
    ]
