# Generated by Django 6.0.6 on 2026-06-23 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(default='Kenya Kiambu JKUAT IOT AWS - Conduit@Empathy1', max_length=255)),
                ('sensor_id', models.IntegerField(default=61, unique=True)),
                ('site_name', models.CharField(default='Site JKUAT', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, default=-1.099736, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=37.014528, max_digits=9)),
                ('elevation_m', models.DecimalField(decimal_places=2, default=1523.0, max_digits=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('health', models.IntegerField()),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('battery_charge_status', models.IntegerField(blank=True, null=True)),
                ('cell_signal_strength', models.IntegerField(blank=True, null=True)),
                ('rain_gauge_1', models.FloatField(blank=True, null=True)),
                ('rain_gauge_2', models.FloatField(blank=True, null=True)),
                ('rain_gauge_1_total_today', models.FloatField(blank=True, null=True)),
                ('rain_gauge_2_total_today', models.FloatField(blank=True, null=True)),
                ('rain_gauge_1_total_prior', models.FloatField(blank=True, null=True)),
                ('rain_gauge_2_total_prior', models.FloatField(blank=True, null=True)),
                ('bmx_temperature', models.FloatField(blank=True, null=True)),
                ('mcp_temperature', models.FloatField(blank=True, null=True)),
                ('sht_temperature', models.FloatField(blank=True, null=True)),
                ('sht_humidity', models.FloatField(blank=True, null=True)),
                ('bmx_pressure', models.FloatField(blank=True, null=True)),
                ('visible_light', models.FloatField(blank=True, null=True)),
                ('infrared', models.FloatField(blank=True, null=True)),
                ('ultraviolet', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField(blank=True, null=True)),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('wind_gust_direction', models.FloatField(blank=True, null=True)),
                ('heat_index', models.FloatField(blank=True, null=True)),
                ('wet_bulb_temperature', models.FloatField(blank=True, null=True)),
                ('wbgt', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='telemetry.weatherstation')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('extreme', 'Extreme')], max_length=20)),
                ('message', models.TextField()),
                ('wbgt', models.FloatField(blank=True, null=True)),
                ('heat_index', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.weathermeasurement')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.weatherstation')),
            ],
        ),
    ]
