from django.contrib import admin

from .models import Alert, WebhookDelivery, WebhookSubscription


@admin.register(Alert)
class AlertAdmin(admin.ModelAdmin):
    list_display = ("alert_type", "severity", "station", "is_active", "created_at")
    list_filter = ("alert_type", "severity", "is_active")
    search_fields = ("station__instrument_name", "message")
    # Alerts are system-generated by the rule-based services; only allow
    # manually closing one out (e.g. a false positive) from the admin.
    readonly_fields = [
        field.name for field in Alert._meta.fields if field.name not in ("is_active", "resolved_at")
    ]


@admin.register(WebhookSubscription)
class WebhookSubscriptionAdmin(admin.ModelAdmin):
    list_display = ("url", "user", "alert_type", "station", "is_active", "created_at")
    list_filter = ("is_active", "alert_type")
    search_fields = ("url", "user__email")
    readonly_fields = ("id", "secret", "created_at")


@admin.register(WebhookDelivery)
class WebhookDeliveryAdmin(admin.ModelAdmin):
    list_display = ("event_type", "subscription", "success", "response_status", "attempt_count", "created_at")
    list_filter = ("success", "event_type")
    search_fields = ("subscription__url",)
    readonly_fields = [field.name for field in WebhookDelivery._meta.fields]
